class Monster < ActiveHash::Base
self.data = [
  {id: 0, name: 'モンスター名' },
  {id: 1, name: 'ランクSSS' },
  {id: 2, name: 'アクバー' },
  {id: 3, name: 'アトラス' },
  {id: 4, name: 'キングヒドラ' },
  {id: 5, name: 'グラコス' },
  {id: 6, name: 'ジャミラス' },
  {id: 7, name: 'デュラン' },
  {id: 8, name: 'バズズ' },
  {id: 9, name: 'バラモスゾンビ' },
  {id: 10, name: 'バラモスブロス' },
  {id: 11, name: 'ベリアル' },
  {id: 12, name: 'ランクSS' },
  {id: 13, name: 'エンゼルスライム' },
  {id: 14, name: 'キラーマジンガ' },
  {id: 15, name: 'ネクロバルサ' },
  {id: 16, name: 'プラチナキング' },
  {id: 17, name: 'ヘルバトラー' },
  {id: 18, name: 'メカバーン' },
  {id: 19, name: 'レジェンドホース' },
  {id: 20, name: 'わたぼう' },
  {id: 21, name: 'ランクS' },
  {id: 22, name: 'アスタロト' },
  {id: 23, name: 'キラーピッケル' },
  {id: 24, name: 'キングエレファント' },
  {id: 25, name: 'ゴールデンコーン' },
  {id: 26, name: 'スイーツトロル' },
  {id: 27, name: 'スウィートバッグ' },
  {id: 28, name: 'タイプG' },
  {id: 29, name: 'ちょうろうじゅ' },
  {id: 30, name: 'つむりんママ' },
  {id: 31, name: 'ツンドラキー' },
  {id: 32, name: 'ピンクボンボン' },
  {id: 33, name: 'べビンゴサタン' },
  {id: 34, name: 'マッドスミス' },
  {id: 35, name: 'ミケまどう' },
  {id: 36, name: 'ムーンキメラ' },
  {id: 37, name: 'メタルキング' },
  {id: 38, name: 'メタルスライム' },
  {id: 39, name: 'メタルホイミン' },
  {id: 40, name: 'モッツァレーラ' },
  {id: 41, name: '死のカラステング' },
  {id: 42, name: 'ランクA' },
  {id: 43, name: 'エビルトレント' },
  {id: 44, name: 'エメラルドーン' },
  {id: 45, name: 'おどるほうせき' },
  {id: 46, name: 'ガーゴイル' },
  {id: 47, name: 'ガネーシャエビル' },
  {id: 48, name: 'キラーマシン' },
  {id: 49, name: 'クイーンスライム' },
  {id: 50, name: 'くろカビこぞう' },
  {id: 51, name: 'スターキメラ' },
  {id: 52, name: 'スライムタワー' },
  {id: 53, name: 'ダークペルシャ' },
  {id: 54, name: 'つららスライム' },
  {id: 55, name: 'ドラキーマ' },
  {id: 56, name: 'トロルキング' },
  {id: 57, name: 'ファーラット' },
  {id: 58, name: 'ブラバニクイーン' },
  {id: 59, name: 'ブランマトック' },
  {id: 60, name: 'ベホマスライム' },
  {id: 61, name: 'ミニデーモン' },
  {id: 62, name: 'リビングデッド' },
  {id: 63, name: 'ランクB' },
  {id: 64, name: 'ベンガルクーン' }
]

include ActiveHash::Associations
has_many :decks

end